#include "cborigin.h"

int get_code_block_origin_type(struct CodeBlockOrigin *origin) {
	const char *instruction = origin->instruction;
	return (instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_OS)? CODE_BLOCK_ORIGIN_TYPE_OS :
			(instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_INTERRUPTION)? CODE_BLOCK_ORIGIN_TYPE_INTERRUPTION :
			(instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CONTINUE)? CODE_BLOCK_ORIGIN_TYPE_CONTINUE :
			(instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_TWO_BEHIND)? CODE_BLOCK_ORIGIN_TYPE_CALL_TWO_BEHIND :
			(instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_THREE_BEHIND)? CODE_BLOCK_ORIGIN_TYPE_CALL_THREE_BEHIND :
			(instruction == CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_FOUR_BEHIND)? CODE_BLOCK_ORIGIN_TYPE_CALL_FOUR_BEHIND :
			CODE_BLOCK_ORIGIN_TYPE_JUMP;
}

void set_os_type_in_code_block_origin(struct CodeBlockOrigin *origin) {
	origin->instruction = CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_OS;
}

int is_valid_instruction_value(const char *instruction) {
	return instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_OS &&
			instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_INTERRUPTION &&
			instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CONTINUE &&
			instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_TWO_BEHIND &&
			instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_THREE_BEHIND &&
			instruction != CODE_BLOCK_ORIGIN_INSTRUCTION_VALUE_TYPE_CALL_FOUR_BEHIND;
}
