#ifndef _REFERENCE_DEFINITIONS_H_
#define _REFERENCE_DEFINITIONS_H_

#define REF_FLAG_TARGET_TYPE_MASK 1
#define REF_FLAG_TARGET_IS_GVAR 0
#define REF_FLAG_TARGET_IS_CBLOCK 1

#define REF_FLAG_WHERE_IN_INSTRUCTION_MASK 2
#define REF_FLAG_IN_INSTRUCTION_ADDRESS 2
#define REF_FLAG_IN_INSTRUCTION_IMMEDIATE_VALUE 0

#define REF_FLAG_ACCESS_MASK 0x0C
#define REF_FLAG_ACCESS_READ 0x04
#define REF_FLAG_ACCESS_WRITE 0x08

#endif /* _REFERENCE_DEFINITIONS_H_ */
